projeto-financer/crud/cadastro/urls.py
from django.urls import path
#from .views import *
from . import views

app_name = 'cadastro'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home')
]

"""
urlpatterns = [
    path('', login, name='login'),
    path('listagem', listar_registros, name='listar_registros'),
    path('novo-registro', criar_registro, name='criar_registro'),
    path('atualizar-registro/<int:id>', atualizar_registro, name='atualizar_registro'),
    path('apagar-registro/<int:id>', apagar_registro, name='apagar_registro'),
    path('criar-conta', criar_conta, name='criar_conta'),
    path('test_login', test_login, name='test_login'),
]
"""

projeto-financer/crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cadastro.urls')),
    path('accounts/', include('allauth.urls')),
]

projeto-financer/crud/cadastro/models.py
from django.db import models


# Create your models here.
class Registro(models.Model):
    price = models.DecimalField(max_digits=9, decimal_places=2)
    date = models.DateField(auto_now_add=True)
    description = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    #account = models.ForeignKey('Conta', on_delete=models.CASCADE)
    account = models.CharField(max_length=255)

    def __str__(self):
        return self.description


class Conta(models.Model):
    name = models.CharField(max_length=50)
    balance = models.DecimalField(max_digits=9, decimal_places=2)

    def __str__(self):
        return self.name

projeto-financer/crud/cadastro/forms.py
from django import forms
from .models import Registro, Conta


class RegistroForm(forms.ModelForm):
    class Meta:
        model = Registro
        fields = ['price', 'description', 'category', 'account']


class ContaForm(forms.ModelForm):
    class Meta:
        model = Conta
        fields = '__all__'

projeto-financer/crud/cadastro/views.py
from django.views.generic import TemplateView
from django.urls import path, include
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Registro, Conta
from .forms import RegistroForm, ContaForm

# views relacionada aos registros
def login(request):
    return redirect('accounts/signup/')

def listar_registros(request):
    registros = Registro.objects.all()
    return render(request, 'listar_registros.html', {'registros': registros})

def criar_registro(request):
    form = RegistroForm(request.POST or None)

    if form.is_valid():
        form.save()
        messages.success(request, "Registro cirado com sucesso!")

        return redirect('listar_registros')
    return render(request, 'registro_form.html', {'form': form})

def atualizar_registro(request, id):
    registro = Registro.objects.get(id=id)
    form = RegistroForm(request.POST or None, instance=registro)

    if form.is_valid():
        form.save()
        messages.success(request, "Registro cirado com sucesso!")

        return redirect('listar_registros')
    return render(request, 'registro_form.html', {'form': form, 'registro': registro})

def apagar_registro(request, id):
    registro = Registro.objects.get(id=id)
    registro.delete()
    return redirect('listar_registros')

# views relacionadas as contas
def criar_conta(request):
    form = ContaForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('listar_registros')
    return render(request, 'conta_form.html', {'form': form})

def test_login(request):
    return render(request, 'test_login.html')

class HomePageView(TemplateView):
    template_name = 'home.html'

projeto-financer/crud/cadastro/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Financer - Registro de Finanças</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon-16x16.png' %}">
</head>
<body>
<nav id="navbar">
    <div>
        <a href="/">Início</a>
        <a href="#">Registros</a>
        <a href="#">Contas</a>
    </div>
    <div>
        <a href="#">G</a>
    </div>
</nav>
<main class="body-container">
    <div class="body-content">
        <h1>Registro de gastos</h1>
        {% block content %}
        {% endblock %}
    </div>
</main>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
        integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT"
        crossorigin="anonymous"></script>
</body>
</html>

projeto-financer/crud/cadastro/templates/conta_form.html
{% extends 'base.html' %}

{% block content %}
    <h2>Criar conta</h2>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">SALVAR CONTA</button>
    </form>
{% endblock %}

projeto-financer/crud/cadastro/templates/home.html
{% extends 'test.html' %}
{% block title %}Loja Python{% endblock %}

{% block content %}
  Debug Mode On
{% endblock %}

projeto-financer/crud/cadastro/templates/listar_registros.html
{% extends 'base.html' %}

{% block content %}
<button class="novo-registro">
    <a href="{% url 'criar_registro' %}"><i class="bi bi-plus-circle-fill"></i><h5>Novo Registro</h5></a>
</button>
<br>
<br>
<br>
<button class="">
    <a href="{% url 'criar_conta' %}"><i class="bi bi-plus-circle-fill"></i><h5>Nova Conta</h5></a>
</button>

<ul>
    {% for registro in registros %}
    <li>
        <div id="descriptions"> <span>Data</span>  <span>Descrição</span>  <span>Valor</span>  <span>Conta</span></div>
        <div id="informatios">
            <span>{{ registro.date }}</span><span> {{ registro.description }}</span> <span> R${{ registro.price }}</span>  <span>{{ registro.account }} </span> 
        </div>

        <button class="editar-registro">
            <a href="{% url 'atualizar_registro' registro.id %}"><i class="bi bi-pencil-fill"></i>EDITAR</a>
        </button>
        <button class="apagar-registro">
            <a href="{% url 'apagar_registro' registro.id %}"><i class="bi bi-trash-fill"></i>APAGAR REGISTRO</a>
        </button>
    </li>
    {% endfor %}
</ul>

<ul>
    {% for conta in contas %}
    <li>
        <div>
            <span>Nome</span>  <span>Saldo</span>
        </div>
        <div>
            <span>{{ conta.name }}</span> <span>{{ conta.balance }}</span>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}

projeto-financer/crud/cadastro/templates/navbar.html
{% load static %}

{% block navbar %}
    <nav id="navbar">
        <div>
            <a href="/">Início</a>
            <a href="#">Registros</a>
            <a href="#">Contas</a>
        </div>
        <div>
            <a href="#">G</a>
        </div>
    </nav>
{% endblock %}

projeto-financer/crud/cadastro/templates/registro_form.html
{% extends 'base.html' %}

{% block content %}

    <h2>Criar / Atualizar registro</h2>

    <form action="" method="POST">

        {% csrf_token %}
        {{ form }}
        <button type="submit">SALVAR REGISTRO</button>

    </form>

{% endblock %}

projeto-financer/crud/cadastro/templates/test.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'cadastro:home' %}">Loja Python</a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>